2017-12-25 19:54:50.709 [error] <0.65.0>@test:test:6 test error
2017-12-30 16:49:38.582 [error] <0.108.0>@gb_reader:login_parse_packet:60 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in call to erlang:binary_to_list(5120) in gb_reader:login_parse_packet/2 line 60
2017-12-30 16:49:38.583 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2017-12-30 16:50:49.432 [error] <0.97.0> CRASH REPORT Process <0.97.0> with 0 neighbours exited with reason: {cannot_listen,eaddrinuse} in gen_server:init_it/6 line 344
2017-12-30 16:50:49.433 [error] <0.95.0> Supervisor {<0.95.0>,gb_tcp_listener_sup} had child gb_tcp_listener started with gb_tcp_listener:start_link(10, 6666) at undefined exit with reason {cannot_listen,eaddrinuse} in context start_error
2017-12-30 16:50:49.433 [error] <0.91.0>@gb_network:start_tcp:52 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{shutdown,{failed_to_start_child,gb_tcp_listener,{cannot_listen,eaddrinuse}}},{child,undefined,gb_tcp_listener_sup,{gb_tcp_listener_sup,start_link,[6666]},transient,infinity,supervisor,[tcp_listener_sup]}}} in gb_network:start_tcp/1 line 52 in application_master:init/4 line 134
2017-12-30 18:23:30.435 [error] <0.108.0>@protobuffs:decode:225 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in call to protobuffs:decode_value(<<0,0,0,10,5,97,103,108,97,98,18,3,49>>, 4, string) line 364 in protobuffs:decode/2 line 225
2017-12-30 18:23:30.436 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2017-12-30 18:31:35.090 [error] <0.108.0>@player_pb:decode CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: call to undefined function player_pb:decode(<<12,0,0,0,10,5,97,103,108,97,98,18,3,49>>)
2017-12-30 18:31:35.090 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason undef in context child_terminated
2017-12-30 18:39:01.805 [error] <0.108.0>@protobuffs:decode:225 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in call to protobuffs:decode_value(<<0,0,0,10,5,97,103,108,97,98,18,3,49>>, 4, string) line 364 in protobuffs:decode/2 line 225
2017-12-30 18:39:01.805 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2017-12-30 18:45:55.013 [error] <0.108.0>@protobuffs:decode:225 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in call to protobuffs:decode_value(<<0,0,0,10,5,97,103,108,97,98,18,3,49>>, 4, string) line 364 in protobuffs:decode/2 line 225
2017-12-30 18:45:55.013 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2017-12-30 19:01:01.728 [error] <0.108.0>@lager:info CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: call to undefined function lager:info("protobuffs Bytes: ~p", [{<<12,0,0,0,10,5,97,103,108,97,98,18,3,49>>,string}])
2017-12-30 19:01:01.728 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason undef in context child_terminated
2017-12-30 19:04:33.658 [error] <0.114.0>@protobuffs:decode:226 CRASH REPORT Process <0.114.0> with 0 neighbours crashed with reason: bad argument in call to protobuffs:decode_value(<<0,0,0,10,5,97,103,108,97,98,18,3,49>>, 4, string) line 365 in protobuffs:decode/2 line 226
2017-12-30 19:04:33.658 [error] <0.100.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.114.0> exit with reason badarg in context child_terminated
2017-12-30 19:07:11.381 [error] <0.108.0>@protobuffs:decode:227 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in call to protobuffs:decode_value(<<0,0,0,10,5,97,103,108,97,98,18,3,49>>, 4, string) line 366 in protobuffs:decode/2 line 227
2017-12-30 19:07:11.381 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2017-12-30 19:12:15.928 [error] <0.108.0>@protobuffs:decode:228 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in call to protobuffs:decode_value(<<0,0,0,10,5,97,103,108,97,98,18,3,49>>, 4, string) line 367 in protobuffs:decode/2 line 228
2017-12-30 19:12:15.928 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2017-12-30 19:16:47.854 [error] <0.109.0>@protobuffs:decode:228 CRASH REPORT Process <0.109.0> with 0 neighbours crashed with reason: bad argument in call to protobuffs:decode_value(<<0,0,0,10,5,97,103,108,97,98,18,3,49>>, 4, string) line 367 in protobuffs:decode/2 line 228
2017-12-30 19:16:47.854 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.109.0> exit with reason badarg in context child_terminated
2017-12-30 19:18:35.003 [error] <0.110.0>@protobuffs:decode:228 CRASH REPORT Process <0.110.0> with 0 neighbours crashed with reason: bad argument in call to protobuffs:decode_value(<<0,0,0,10,5,97,103,108,97,98,18,3,49>>, 4, string) line 367 in protobuffs:decode/2 line 228
2017-12-30 19:18:35.003 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.110.0> exit with reason badarg in context child_terminated
2017-12-30 19:20:51.424 [error] <0.111.0>@protobuffs:decode:228 CRASH REPORT Process <0.111.0> with 0 neighbours crashed with reason: bad argument in call to protobuffs:decode_value(<<0,0,0,10,5,97,103,108,97,98,18,3,49>>, 4, string) line 367 in protobuffs:decode/2 line 228
2017-12-30 19:20:51.425 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.111.0> exit with reason badarg in context child_terminated
2017-12-30 19:24:28.441 [error] <0.112.0>@protobuffs:decode:228 CRASH REPORT Process <0.112.0> with 0 neighbours crashed with reason: bad argument in call to protobuffs:decode_value(<<0,0,0,10,5,97,103,108,97,98,18,3,49>>, 4, string) line 367 in protobuffs:decode/2 line 228
2017-12-30 19:24:28.441 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.112.0> exit with reason badarg in context child_terminated
2017-12-30 19:48:38.085 [error] <0.108.0>@protobuffs:decode_value:330 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in call to erlang:split_binary(<<"1">>, 3) in protobuffs:decode_value/3 line 330
2017-12-30 19:48:38.085 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2017-12-30 19:57:42.086 [error] <0.108.0>@protobuffs:decode_value:330 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in call to erlang:split_binary(<<"1">>, 3) in protobuffs:decode_value/3 line 330
2017-12-30 19:57:42.087 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2017-12-30 20:26:14.746 [error] <0.108.0>@pt_10:encode CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: call to undefined function pt_10:encode({c2s_login_request,"hello world","world"})
2017-12-30 20:26:14.747 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason undef in context child_terminated
2017-12-30 20:27:57.404 [error] <0.97.0> CRASH REPORT Process <0.97.0> with 0 neighbours exited with reason: {cannot_listen,eaddrinuse} in gen_server:init_it/6 line 344
2017-12-30 20:27:57.404 [error] <0.95.0> Supervisor {<0.95.0>,gb_tcp_listener_sup} had child gb_tcp_listener started with gb_tcp_listener:start_link(10, 6666) at undefined exit with reason {cannot_listen,eaddrinuse} in context start_error
2017-12-30 20:27:57.404 [error] <0.91.0>@gb_network:start_tcp:52 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{shutdown,{failed_to_start_child,gb_tcp_listener,{cannot_listen,eaddrinuse}}},{child,undefined,gb_tcp_listener_sup,{gb_tcp_listener_sup,start_link,[6666]},transient,infinity,supervisor,[tcp_listener_sup]}}} in gb_network:start_tcp/1 line 52 in application_master:init/4 line 134
2017-12-30 20:29:27.890 [error] <0.108.0>@player_pb:iolist CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: call to undefined function player_pb:iolist(c2s_login_request, {c2s_login_request,"hello world","world"})
2017-12-30 20:29:27.890 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason undef in context child_terminated
2017-12-30 21:03:00.544 [error] <0.108.0>@player_pb:decode_s2c_login_request CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: call to undefined function player_pb:decode_s2c_login_request(<<10,11,104,101,108,108,111,32,119,111,114,108,100,18,5,119,111,114,108,100>>)
2017-12-30 21:03:00.544 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason undef in context child_terminated
2018-01-01 18:26:48.040 [error] <0.108.0> CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: {error,"Error decoding type"} in protobuffs:read_field_num_and_wire_type/1 line 212
2018-01-01 18:26:48.040 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason {error,"Error decoding type"} in context child_terminated
2018-01-01 18:42:08.361 [error] <0.110.0>@gb_reader:login_parse_packet:67 CRASH REPORT Process <0.110.0> with 0 neighbours crashed with reason: bad argument in call to erlang:length(<<10,11,104,101,108,108,111,32,119,111,114,108,100,18,5,119,111,114,108,100>>) in gb_reader:login_parse_packet/2 line 67
2018-01-01 18:42:08.361 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.110.0> exit with reason badarg in context child_terminated
2018-01-01 18:44:19.445 [error] <0.108.0>@gb_reader:login_parse_packet:67 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in call to erlang:list_to_binary(20) in gb_reader:login_parse_packet/2 line 67
2018-01-01 18:44:19.445 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2018-01-01 18:47:14.836 [error] <0.108.0>@gb_reader:login_parse_packet:68 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: no match of right hand value <<20>> in gb_reader:login_parse_packet/2 line 68
2018-01-01 18:47:14.837 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason {badmatch,<<20>>} in context child_terminated
2018-01-01 18:54:20.640 [error] <0.108.0>@erlang:atom_to_binary CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: call to undefined function erlang:atom_to_binary(20)
2018-01-01 18:54:20.640 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason undef in context child_terminated
2018-01-01 18:58:47.768 [error] <0.108.0>@gb_reader:login_parse_packet:70 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in gb_reader:login_parse_packet/2 line 70
2018-01-01 18:58:47.768 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2018-01-01 19:39:13.850 [error] <0.97.0> CRASH REPORT Process <0.97.0> with 0 neighbours exited with reason: {cannot_listen,eaddrinuse} in gen_server:init_it/6 line 344
2018-01-01 19:39:13.850 [error] <0.95.0> Supervisor {<0.95.0>,gb_tcp_listener_sup} had child gb_tcp_listener started with gb_tcp_listener:start_link(10, 6666) at undefined exit with reason {cannot_listen,eaddrinuse} in context start_error
2018-01-01 19:39:13.851 [error] <0.91.0>@gb_network:start_tcp:52 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{shutdown,{failed_to_start_child,gb_tcp_listener,{cannot_listen,eaddrinuse}}},{child,undefined,gb_tcp_listener_sup,{gb_tcp_listener_sup,start_link,[6666]},transient,infinity,supervisor,[tcp_listener_sup]}}} in gb_network:start_tcp/1 line 52 in application_master:init/4 line 134
2018-01-01 19:58:04.949 [error] <0.108.0>@gb_reader:login_parse_packet:69 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in gb_reader:login_parse_packet/2 line 69
2018-01-01 19:58:04.949 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2018-01-01 20:00:39.819 [error] emulator Bad value on output port 'tcp_inet'

2018-01-01 20:00:39.819 [error] <0.108.0>@gb_reader:login_parse_packet:79 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: no match of right hand value {error,einval} in gb_reader:login_parse_packet/2 line 79
2018-01-01 20:00:39.819 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason {badmatch,{error,einval}} in context child_terminated
2018-01-02 14:44:54.024 [error] <0.108.0>@protobuffs:decode:225 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in call to protobuffs:decode_value(<<0,0,0,10,5,97,103,108,97,98,18,3,49>>, 4, string) line 364 in protobuffs:decode/2 line 225
2018-01-02 14:44:54.025 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2018-01-02 14:52:26.536 [error] <0.109.0>@protobuffs:decode:225 CRASH REPORT Process <0.109.0> with 0 neighbours crashed with reason: bad argument in call to protobuffs:decode_value(<<0,0,0,10,11,104,101,108,108,111,32,119,111,114,108,100,18,5,104,101,108>>, 4, string) line 364 in protobuffs:decode/2 line 225
2018-01-02 14:52:26.536 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.109.0> exit with reason badarg in context child_terminated
2018-01-02 14:55:04.289 [error] <0.110.0>@protobuffs:decode_value:330 CRASH REPORT Process <0.110.0> with 0 neighbours crashed with reason: bad argument in call to erlang:split_binary(<<"hel">>, 5) in protobuffs:decode_value/3 line 330
2018-01-02 14:55:04.289 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.110.0> exit with reason badarg in context child_terminated
2018-01-02 14:56:39.240 [error] <0.111.0>@protobuffs:decode_value:330 CRASH REPORT Process <0.111.0> with 0 neighbours crashed with reason: bad argument in call to erlang:split_binary(<<"wor">>, 5) in protobuffs:decode_value/3 line 330
2018-01-02 14:56:39.240 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.111.0> exit with reason badarg in context child_terminated
2018-01-02 15:26:45.132 [error] <0.108.0>@pt_10:encode:115 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in pt_10:encode/2 line 115
2018-01-02 15:26:45.132 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2018-01-02 15:27:20.403 [error] <0.109.0>@pt_10:encode:115 CRASH REPORT Process <0.109.0> with 0 neighbours crashed with reason: bad argument in pt_10:encode/2 line 115
2018-01-02 15:27:20.403 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.109.0> exit with reason badarg in context child_terminated
2018-01-02 15:29:38.172 [error] <0.108.0>@pt_10:encode:116 CRASH REPORT Process <0.108.0> with 0 neighbours crashed with reason: bad argument in pt_10:encode/2 line 116
2018-01-02 15:29:38.172 [error] <0.94.0> Supervisor gb_tcp_client_sup had child gb_reader started with {gb_reader,start_link,undefined} at <0.108.0> exit with reason badarg in context child_terminated
2018-01-02 19:50:45.650 [error] <0.94.0>@mysql:start_link CRASH REPORT Process <0.94.0> with 0 neighbours exited with reason: call to undefined function mysql:start_link(db, "localhost", 3306, "root", "184514", "gb_mysql_conn", #Fun<mod_kernel.0.13706730>, utf8) in gen_server:init_it/6 line 352
2018-01-02 19:50:45.650 [error] <0.91.0>@gb_network:start_kernel:22 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{undef,[{mysql,start_link,[db,"localhost",3306,"root","184514","gb_mysql_conn",#Fun<mod_kernel.0.13706730>,utf8],[]},{mod_kernel,init_mysql,0,[{file,"src/mod/mod_kernel.erl"},{line,63}]},{mod_kernel,init,1,[{file,"src/mod/mod_kernel.erl"},{line,41}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{child,undefined,mod_kernel,{mod_kernel,start_link,[]},permanent,10000,supervisor,[mod_kernel]}}} in gb_network:start_kernel/0 line 22 in application_master:init/4 line 134
2018-01-02 19:53:15.378 [error] <0.94.0>@mysql:start_link CRASH REPORT Process <0.94.0> with 0 neighbours exited with reason: call to undefined function mysql:start_link(db, "localhost", 3306, "root", "184514", "gb_mysql_conn", #Fun<mod_kernel.0.13706730>, utf8) in gen_server:init_it/6 line 352
2018-01-02 19:53:15.378 [error] <0.91.0>@gb_network:start_kernel:22 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{undef,[{mysql,start_link,[db,"localhost",3306,"root","184514","gb_mysql_conn",#Fun<mod_kernel.0.13706730>,utf8],[]},{mod_kernel,init_mysql,0,[{file,"src/mod/mod_kernel.erl"},{line,63}]},{mod_kernel,init,1,[{file,"src/mod/mod_kernel.erl"},{line,41}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{child,undefined,mod_kernel,{mod_kernel,start_link,[]},permanent,10000,supervisor,[mod_kernel]}}} in gb_network:start_kernel/0 line 22 in application_master:init/4 line 134
2018-01-02 19:55:08.957 [error] <0.94.0>@mysql:start_link CRASH REPORT Process <0.94.0> with 0 neighbours exited with reason: call to undefined function mysql:start_link(db, "localhost", 3306, "root", "184514", "gb_center", #Fun<mod_kernel.0.26305797>, utf8) in gen_server:init_it/6 line 352
2018-01-02 19:55:08.957 [error] <0.91.0>@gb_network:start_kernel:22 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{undef,[{mysql,start_link,[db,"localhost",3306,"root","184514","gb_center",#Fun<mod_kernel.0.26305797>,utf8],[]},{mod_kernel,init_mysql,0,[{file,"src/mod/mod_kernel.erl"},{line,63}]},{mod_kernel,init,1,[{file,"src/mod/mod_kernel.erl"},{line,41}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{child,undefined,mod_kernel,{mod_kernel,start_link,[]},permanent,10000,supervisor,[mod_kernel]}}} in gb_network:start_kernel/0 line 22 in application_master:init/4 line 134
2018-01-02 19:58:14.888 [error] <0.94.0>@mysql:start_link CRASH REPORT Process <0.94.0> with 0 neighbours exited with reason: call to undefined function mysql:start_link(db, "localhost", 3306, "root", [], "gb_center", #Fun<mod_kernel.0.65060746>, utf8) in gen_server:init_it/6 line 352
2018-01-02 20:19:00.616 [error] emulator Error in process <0.98.0> with exit value:
{badarg,[{erlang,iolist_to_binary,[184514],[]},{crypto,hash,2,[{file,"crypto.erl"},{line,225}]},{mysql_auth,password_new,2,[{file,"src/mysql_auth.erl"},{line,195}]},{mysql_auth,do_new_auth,9,[{file,"src/mysql_auth.erl"},{line,79}]},{mysql_conn,mysql_init,6,[{file,"src/mysql_conn.erl"},{line,622}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,347}]}]}
2018-01-02 20:19:05.601 [error] emulator Error in process <0.103.0> with exit value:
{badarg,[{erlang,iolist_to_binary,[184514],[]},{crypto,hash,2,[{file,"crypto.erl"},{line,225}]},{mysql_auth,password_new,2,[{file,"src/mysql_auth.erl"},{line,195}]},{mysql_auth,do_new_auth,9,[{file,"src/mysql_auth.erl"},{line,79}]},{mysql_conn,mysql_init,6,[{file,"src/mysql_conn.erl"},{line,622}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,347}]}]}
2018-01-02 20:19:05.602 [error] emulator Error in process <0.104.0> with exit value:
{badarg,[{erlang,iolist_to_binary,[184514],[]},{crypto,hash,2,[{file,"crypto.erl"},{line,225}]},{mysql_auth,password_new,2,[{file,"src/mysql_auth.erl"},{line,195}]},{mysql_auth,do_new_auth,9,[{file,"src/mysql_auth.erl"},{line,79}]},{mysql_conn,mysql_init,6,[{file,"src/mysql_conn.erl"},{line,622}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,347}]}]}
2018-01-02 20:19:05.602 [error] <0.91.0>@gb_network:start_kernel:22 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{badarg,[{erlang,iolist_to_binary,[184514],[]},{crypto,hash,2,[{file,"crypto.erl"},{line,225}]},{mysql_auth,password_new,2,[{file,"src/mysql_auth.erl"},{line,195}]},{mysql_auth,do_new_auth,9,[{file,"src/mysql_auth.erl"},{line,79}]},{mysql_conn,mysql_init,6,[{file,"src/mysql_conn.erl"},{line,622}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,347}]}]},{child,undefined,mod_kernel,{mod_kernel,start_link,[]},permanent,10000,supervisor,[mod_kernel]}}} in gb_network:start_kernel/0 line 22 in application_master:init/4 line 134
2018-01-02 20:20:04.649 [error] emulator Error in process <0.98.0> with exit value:
{badarg,[{erlang,iolist_to_binary,[184514],[]},{crypto,hash,2,[{file,"crypto.erl"},{line,225}]},{mysql_auth,password_new,2,[{file,"src/mysql_auth.erl"},{line,195}]},{mysql_auth,do_new_auth,9,[{file,"src/mysql_auth.erl"},{line,79}]},{mysql_conn,mysql_init,6,[{file,"src/mysql_conn.erl"},{line,622}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,347}]}]}
2018-01-02 20:20:09.641 [error] emulator Error in process <0.104.0> with exit value:
{badarg,[{erlang,iolist_to_binary,[184514],[]},{crypto,hash,2,[{file,"crypto.erl"},{line,225}]},{mysql_auth,password_new,2,[{file,"src/mysql_auth.erl"},{line,195}]},{mysql_auth,do_new_auth,9,[{file,"src/mysql_auth.erl"},{line,79}]},{mysql_conn,mysql_init,6,[{file,"src/mysql_conn.erl"},{line,622}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,347}]}]}
2018-01-02 20:20:09.642 [error] emulator Error in process <0.103.0> with exit value:
{badarg,[{erlang,iolist_to_binary,[184514],[]},{crypto,hash,2,[{file,"crypto.erl"},{line,225}]},{mysql_auth,password_new,2,[{file,"src/mysql_auth.erl"},{line,195}]},{mysql_auth,do_new_auth,9,[{file,"src/mysql_auth.erl"},{line,79}]},{mysql_conn,mysql_init,6,[{file,"src/mysql_conn.erl"},{line,622}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,347}]}]}
2018-01-02 20:52:28.427 [error] <0.94.0>@mysql:start_link CRASH REPORT Process <0.94.0> with 0 neighbours exited with reason: call to undefined function mysql:start_link(db, "localhost", 3306, "root", "184514", "gb_center", #Fun<mod_kernel.0.26305797>, utf8) in gen_server:init_it/6 line 352
2018-01-03 19:00:54.991 [error] <0.91.0>@gb_network:start:13 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: bad arithmetic expression in gb_network:start/1 line 13 in application_master:init/4 line 134
2018-01-03 19:04:04.270 [error] emulator Error in process <0.98.0> with exit value:
{function_clause,[{mysql_recv,start_link,["localhost","3306",#Fun<mod_kernel.0.17981621>,<0.98.0>],[{file,"src/mysql_recv.erl"},{line,73}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,345}]}]}
2018-01-03 19:04:09.272 [error] emulator Error in process <0.100.0> with exit value:
{function_clause,[{mysql_recv,start_link,["localhost","3306",#Fun<mod_kernel.0.17981621>,<0.100.0>],[{file,"src/mysql_recv.erl"},{line,73}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,345}]}]}
2018-01-03 19:04:14.271 [error] emulator Error in process <0.115.0> with exit value:
{function_clause,[{mysql_recv,start_link,["localhost","3306",#Fun<mod_kernel.0.17981621>,<0.115.0>],[{file,"src/mysql_recv.erl"},{line,73}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,345}]}]}
2018-01-03 19:04:19.272 [error] emulator Error in process <0.116.0> with exit value:
{function_clause,[{mysql_recv,start_link,["localhost","3306",#Fun<mod_kernel.0.17981621>,<0.116.0>],[{file,"src/mysql_recv.erl"},{line,73}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,345}]}]}
2018-01-03 19:04:24.273 [error] emulator Error in process <0.117.0> with exit value:
{function_clause,[{mysql_recv,start_link,["localhost","3306",#Fun<mod_kernel.0.17981621>,<0.117.0>],[{file,"src/mysql_recv.erl"},{line,73}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,345}]}]}
2018-01-03 19:04:29.274 [error] emulator Error in process <0.118.0> with exit value:
{function_clause,[{mysql_recv,start_link,["localhost","3306",#Fun<mod_kernel.0.17981621>,<0.118.0>],[{file,"src/mysql_recv.erl"},{line,73}]},{mysql_conn,init,10,[{file,"src/mysql_conn.erl"},{line,345}]}]}
2018-01-04 13:20:21.075 [error] <0.106.0> CRASH REPORT Process <0.106.0> with 0 neighbours exited with reason: {cannot_listen,eaddrinuse} in gen_server:init_it/6 line 344
2018-01-04 13:20:21.075 [error] <0.104.0> Supervisor {<0.104.0>,gb_tcp_listener_sup} had child gb_tcp_listener started with gb_tcp_listener:start_link(10, 6666) at undefined exit with reason {cannot_listen,eaddrinuse} in context start_error
2018-01-04 13:20:21.075 [error] <0.91.0>@gb_network:start_tcp:52 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{shutdown,{failed_to_start_child,gb_tcp_listener,{cannot_listen,eaddrinuse}}},{child,undefined,gb_tcp_listener_sup,{gb_tcp_listener_sup,start_link,[6666]},transient,infinity,supervisor,[tcp_listener_sup]}}} in gb_network:start_tcp/1 line 52 in application_master:init/4 line 134
2018-01-04 13:33:44.160 [error] <0.94.0>@gen_server:init_it:356 CRASH REPORT Process mod_kernel with 0 neighbours exited with reason: bad return value: {failed_to_connect_to_database,econnrefused} in gen_server:init_it/6 line 356
2018-01-04 13:33:44.161 [error] <0.91.0>@gb_network:start_kernel:22 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{bad_return_value,{failed_to_connect_to_database,econnrefused}},{child,undefined,mod_kernel,{mod_kernel,start_link,[]},permanent,10000,supervisor,[mod_kernel]}}} in gb_network:start_kernel/0 line 22 in application_master:init/4 line 134
2018-01-04 13:35:31.608 [error] <0.94.0>@gen_server:init_it:356 CRASH REPORT Process mod_kernel with 0 neighbours exited with reason: bad return value: {failed_to_connect_to_database,econnrefused} in gen_server:init_it/6 line 356
2018-01-04 13:35:31.609 [error] <0.91.0>@gb_network:start_kernel:22 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{bad_return_value,{failed_to_connect_to_database,econnrefused}},{child,undefined,mod_kernel,{mod_kernel,start_link,[]},permanent,10000,supervisor,[mod_kernel]}}} in gb_network:start_kernel/0 line 22 in application_master:init/4 line 134
2018-01-04 15:14:19.175 [error] <0.100.0>@gen_server:init_it:356 CRASH REPORT Process mod_kernel with 0 neighbours exited with reason: bad return value: {failed_to_connect_to_database,econnrefused} in gen_server:init_it/6 line 356
2018-01-04 15:14:19.176 [error] <0.97.0>@gb_network:start_kernel:22 CRASH REPORT Process <0.97.0> with 0 neighbours exited with reason: no match of right hand value {error,{{bad_return_value,{failed_to_connect_to_database,econnrefused}},{child,undefined,mod_kernel,{mod_kernel,start_link,[]},permanent,10000,supervisor,[mod_kernel]}}} in gb_network:start_kernel/0 line 22 in application_master:init/4 line 134
2018-01-04 21:14:54.096 [error] <0.94.0>@mysql:start_link CRASH REPORT Process <0.94.0> with 0 neighbours exited with reason: call to undefined function mysql:start_link(db, "39.106.41.102", 3306, "root", "20157411.adj", "db", #Fun<mod_kernel.0.60528289>, utf8) in gen_server:init_it/6 line 352
2018-01-04 21:26:31.025 [error] <0.94.0>@mysql:start_link CRASH REPORT Process <0.94.0> with 0 neighbours exited with reason: call to undefined function mysql:start_link(db, "39.106.41.102", 3306, "root", "20157411.adj", "db", #Fun<mod_kernel.0.60528289>, utf8) in gen_server:init_it/6 line 352
2018-01-04 21:26:31.025 [error] <0.91.0>@gb_network:start_kernel:22 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{undef,[{mysql,start_link,[db,"39.106.41.102",3306,"root","20157411.adj","db",#Fun<mod_kernel.0.60528289>,utf8],[]},{mod_kernel,init_mysql,0,[{file,"src/mod/mod_kernel.erl"},{line,66}]},{mod_kernel,init,1,[{file,"src/mod/mod_kernel.erl"},{line,41}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{child,undefined,mod_kernel,{mod_kernel,start_link,[]},permanent,10000,supervisor,[mod_kernel]}}} in gb_network:start_kernel/0 line 22 in application_master:init/4 line 134
2018-01-04 21:46:30.768 [error] <0.98.0> CRASH REPORT Process <0.98.0> with 0 neighbours exited with reason: {cannot_listen,eaddrinuse} in gen_server:init_it/6 line 344
2018-01-04 21:46:30.768 [error] <0.96.0> Supervisor {<0.96.0>,gb_tcp_listener_sup} had child gb_tcp_listener started with gb_tcp_listener:start_link(10, 6666) at undefined exit with reason {cannot_listen,eaddrinuse} in context start_error
2018-01-04 21:46:30.768 [error] <0.91.0>@gb_network:start_tcp:52 CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: no match of right hand value {error,{{shutdown,{failed_to_start_child,gb_tcp_listener,{cannot_listen,eaddrinuse}}},{child,undefined,gb_tcp_listener_sup,{gb_tcp_listener_sup,start_link,[6666]},transient,infinity,supervisor,[tcp_listener_sup]}}} in gb_network:start_tcp/1 line 52 in application_master:init/4 line 134
